// Code generated by protoc-gen-go. DO NOT EDIT.
// source: consignment/consignment.proto

package consignment

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Consignment struct {
	Id                   string       `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Description          string       `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Weight               int32        `protobuf:"varint,3,opt,name=weight,proto3" json:"weight,omitempty"`
	Containers           []*Container `protobuf:"bytes,4,rep,name=containers,proto3" json:"containers,omitempty"`
	VesselId             string       `protobuf:"bytes,5,opt,name=vessel_id,json=vesselId,proto3" json:"vessel_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Consignment) Reset()         { *m = Consignment{} }
func (m *Consignment) String() string { return proto.CompactTextString(m) }
func (*Consignment) ProtoMessage()    {}
func (*Consignment) Descriptor() ([]byte, []int) {
	return fileDescriptor_2c6f11f9923110da, []int{0}
}

func (m *Consignment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Consignment.Unmarshal(m, b)
}
func (m *Consignment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Consignment.Marshal(b, m, deterministic)
}
func (m *Consignment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Consignment.Merge(m, src)
}
func (m *Consignment) XXX_Size() int {
	return xxx_messageInfo_Consignment.Size(m)
}
func (m *Consignment) XXX_DiscardUnknown() {
	xxx_messageInfo_Consignment.DiscardUnknown(m)
}

var xxx_messageInfo_Consignment proto.InternalMessageInfo

func (m *Consignment) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Consignment) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Consignment) GetWeight() int32 {
	if m != nil {
		return m.Weight
	}
	return 0
}

func (m *Consignment) GetContainers() []*Container {
	if m != nil {
		return m.Containers
	}
	return nil
}

func (m *Consignment) GetVesselId() string {
	if m != nil {
		return m.VesselId
	}
	return ""
}

type Container struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CustomerId           string   `protobuf:"bytes,2,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	Origin               string   `protobuf:"bytes,3,opt,name=origin,proto3" json:"origin,omitempty"`
	UserId               string   `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Container) Reset()         { *m = Container{} }
func (m *Container) String() string { return proto.CompactTextString(m) }
func (*Container) ProtoMessage()    {}
func (*Container) Descriptor() ([]byte, []int) {
	return fileDescriptor_2c6f11f9923110da, []int{1}
}

func (m *Container) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Container.Unmarshal(m, b)
}
func (m *Container) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Container.Marshal(b, m, deterministic)
}
func (m *Container) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Container.Merge(m, src)
}
func (m *Container) XXX_Size() int {
	return xxx_messageInfo_Container.Size(m)
}
func (m *Container) XXX_DiscardUnknown() {
	xxx_messageInfo_Container.DiscardUnknown(m)
}

var xxx_messageInfo_Container proto.InternalMessageInfo

func (m *Container) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Container) GetCustomerId() string {
	if m != nil {
		return m.CustomerId
	}
	return ""
}

func (m *Container) GetOrigin() string {
	if m != nil {
		return m.Origin
	}
	return ""
}

func (m *Container) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type Response struct {
	Created              bool         `protobuf:"varint,1,opt,name=created,proto3" json:"created,omitempty"`
	Consignment          *Consignment `protobuf:"bytes,2,opt,name=consignment,proto3" json:"consignment,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_2c6f11f9923110da, []int{2}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetCreated() bool {
	if m != nil {
		return m.Created
	}
	return false
}

func (m *Response) GetConsignment() *Consignment {
	if m != nil {
		return m.Consignment
	}
	return nil
}

func init() {
	proto.RegisterType((*Consignment)(nil), "consignment.Consignment")
	proto.RegisterType((*Container)(nil), "consignment.Container")
	proto.RegisterType((*Response)(nil), "consignment.Response")
}

func init() {
	proto.RegisterFile("consignment/consignment.proto", fileDescriptor_2c6f11f9923110da)
}

var fileDescriptor_2c6f11f9923110da = []byte{
	// 336 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x52, 0x4d, 0x4b, 0xc3, 0x40,
	0x10, 0x35, 0xfd, 0xce, 0x04, 0x14, 0x17, 0xac, 0x41, 0x11, 0x43, 0x4e, 0xbd, 0xb4, 0x85, 0x0a,
	0x1e, 0x3c, 0x5a, 0x10, 0x82, 0xb7, 0xf4, 0xa4, 0x17, 0x4d, 0x77, 0x87, 0x74, 0xb1, 0xd9, 0x0d,
	0xbb, 0x9b, 0xaa, 0xff, 0xc9, 0x1f, 0x29, 0xd9, 0x34, 0xba, 0x2a, 0x9e, 0x32, 0xef, 0xbd, 0x99,
	0x79, 0x2f, 0xc9, 0xc0, 0x05, 0x95, 0x42, 0xf3, 0x5c, 0x14, 0x28, 0xcc, 0xdc, 0xa9, 0x67, 0xa5,
	0x92, 0x46, 0x92, 0xc0, 0xa1, 0xe2, 0x0f, 0x0f, 0x82, 0xe5, 0x37, 0x26, 0x87, 0xd0, 0xe1, 0x2c,
	0xf4, 0x22, 0x6f, 0xe2, 0xa7, 0x1d, 0xce, 0x48, 0x04, 0x01, 0x43, 0x4d, 0x15, 0x2f, 0x0d, 0x97,
	0x22, 0xec, 0x58, 0xc1, 0xa5, 0xc8, 0x18, 0x06, 0xaf, 0xc8, 0xf3, 0x8d, 0x09, 0xbb, 0x91, 0x37,
	0xe9, 0xa7, 0x7b, 0x44, 0xae, 0x01, 0xa8, 0x14, 0x26, 0xe3, 0x02, 0x95, 0x0e, 0x7b, 0x51, 0x77,
	0x12, 0x2c, 0xc6, 0x33, 0x37, 0xce, 0xb2, 0x95, 0x53, 0xa7, 0x93, 0x9c, 0x83, 0xbf, 0x43, 0xad,
	0x71, 0xfb, 0xc4, 0x59, 0xd8, 0xb7, 0x7e, 0xa3, 0x86, 0x48, 0x58, 0x5c, 0x80, 0xff, 0x35, 0xf5,
	0x27, 0xeb, 0x25, 0x04, 0xb4, 0xd2, 0x46, 0x16, 0xa8, 0xea, 0xd9, 0x26, 0x2b, 0xb4, 0x54, 0xc2,
	0xea, 0xa8, 0x52, 0xf1, 0x9c, 0x0b, 0x1b, 0xd5, 0x4f, 0xf7, 0x88, 0x9c, 0xc2, 0xb0, 0xd2, 0xcd,
	0x50, 0xaf, 0x11, 0x6a, 0x98, 0xb0, 0xf8, 0x19, 0x46, 0x29, 0xea, 0x52, 0x0a, 0x8d, 0x24, 0x84,
	0x21, 0x55, 0x98, 0x19, 0x6c, 0x2c, 0x47, 0x69, 0x0b, 0xc9, 0x0d, 0xb8, 0x9f, 0xd4, 0xfa, 0x06,
	0x8b, 0xf0, 0xf7, 0xab, 0xb6, 0x75, 0xea, 0x36, 0x2f, 0x1e, 0xe0, 0x68, 0xb5, 0xc1, 0xb2, 0xe4,
	0x22, 0x5f, 0xa1, 0xda, 0x71, 0x8a, 0xe4, 0x0e, 0x8e, 0x97, 0x76, 0xb3, 0xfb, 0x5f, 0xfe, 0x5d,
	0x77, 0x76, 0xf2, 0x43, 0x69, 0xe3, 0xc6, 0x07, 0xb7, 0xf7, 0x8f, 0x49, 0xce, 0xcd, 0xa6, 0x5a,
	0xcf, 0xa8, 0x2c, 0xe6, 0xd9, 0x16, 0xdf, 0xa6, 0x52, 0xbd, 0x54, 0x45, 0x36, 0xd7, 0xb5, 0xe3,
	0x7b, 0xfd, 0xc0, 0x72, 0xaa, 0x1b, 0xdb, 0xa9, 0x7b, 0x34, 0xf6, 0x50, 0xdc, 0xd3, 0x59, 0x0f,
	0x2c, 0x75, 0xf5, 0x19, 0x00, 0x00, 0xff, 0xff, 0xc4, 0x85, 0x1f, 0x06, 0x5c, 0x02, 0x00, 0x00,
}
